export const UnitAction = {
    UNIT_APPEND_CHILD: "UNIT_APPEND_CHILD",
    UNIT_CHANGE_TEXT: "UNIT_CHANGE_TEXT",
    UNIT_CREATE_CHILDREN: "UNIT_CREATE_CHILDREN",
    UNIT_INCREMENT_EVENT_COUNT: "UNIT_INCREMENT_EVENT_COUNT"
};